language: python

python:
  - 2.6
  - 2.7
  - pypy
  - 3.3
  - 3.4

install:
  - python -c 'import setup; print(setup.REQUIRES_PIP)' |xargs pip install
  - pip install .

script: python setup.py test

after_success:
  - coveralls_multi_ci submit -v
  - coveralls_multi_ci submit -v --multi
